[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "btree"
version = "0.1.0"
description = "Simple B-Tree implementation in Python."
readme = "README.md"
requires-python = ">=3.7"
