name: Release Tag

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Tag new release
        id: tagger
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: master
          tag_prefix: v
      - name: Echo created tag
        run: echo "Created ${{ steps.tagger.outputs.new_tag }}"
      - name: Set up Python
        if: steps.tagger.outputs.new_tag != ''
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install build dependencies
        if: steps.tagger.outputs.new_tag != ''
        run: |
          python -m pip install --upgrade pip
          pip install build twine
      - name: Build package
        if: steps.tagger.outputs.new_tag != ''
        run: python -m build
      - name: Publish to Artifactory
        if: steps.tagger.outputs.new_tag != ''
        env:
          TWINE_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
          TWINE_REPOSITORY_URL: ${{ secrets.ARTIFACTORY_URL }}
        run: twine upload dist/*
